apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webnest-ingress
  namespace: proyecto-nest
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: nest.megacrossover.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nest-taller
            port:
              number: 3001