apiVersion: v1
kind: Service
metadata:
  name: nest-taller
  namespace: proyecto-nest
spec:
  type: NodePort
  selector:
    app: webnest
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30081