apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.container.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.container.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.container.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.container.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Values.app.container.name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.container.port }}
        - containerPort: {{ .Values.app.service.sshPort }}