apiVersion: v1
kind: Secret
metadata:
  name: postgre-secret
  namespace: proyecto-nest
type: Opaque
data:
  # "postgres" en base64
  POSTGRES_USER: cG9zdGdyZXM=
  # "usuario" en base64
  POSTGRES_PASSWORD: dXN1YXJpbw==
  # "nestasir" en base64
  POSTGRES_DB: bmVzdGFzaXI=
