services:
  web:
    build:
      context: /home/jiahaolin/nest/docker/megacrossover/
      dockerfile: ./dockerfiles/ubbase/jhlwubbase
      args:
        - INICIALES=jhlw
    container_name: ctjhlwbase
    image: jiahaolin69/ubbase
    ports:
      - 22:22
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      pbase_network:
        ipv4_address: 192.168.20.3
networks:
  pbase_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24