services:
  web:
    build:
      context: /home/jiahaolin/nest/docker/megacrossover/
      dockerfile: ./dockerfiles/nginxpokeapi/jhlwnginxpokeapi
      args:
        - INICIALES=jhlw
    container_name: ctjhlwnginxpokeapi
    image: jiahaolin69/nginxpokeapi
    ports:
      - 3010:3001
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      pnautocaravaneando:
        ipv4_address: ${IP_WEB}
networks:
  pnautocaravaneando:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}