services:
  # =============================================
  # PostgreSQL - Base de datos
  # =============================================
  postgresBDusarios:
    image: jiahaolin69/postgre
    container_name: usuarios-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs:/root/logs
    ports:
      - "5432:5432"
    networks:
      - nestpostgre-network
    healthcheck:
      test: ["CMD-SHELL", "su - postgres -c 'pg_isready -U postgres -d nestasir'"]
      interval: 5s
      timeout: 5s
      retries: 10

  # =============================================
  # NestJS - API Backend
  # =============================================
  ms-usuarios-nest:
    build:
      context: ../../nest_api/proyecto/
      dockerfile: ../../proyecto/01_nestpostgresql/deploy/build_img/Dockerfile
    image: jiahaolin69/nestpostgresql
    container_name: caronte-ms-nestpostgresql
    ports:
      - "3001:3001"
    volumes:
      - ./logs:/root/logs
    networks:
      - nestpostgre-network
    depends_on:
      postgresBDusarios:
        condition: service_healthy

# Volumen persistente para PostgreSQL
volumes:
  postgres_data:

# Red interna para comunicaci√≥n entre contenedores
networks:
  nestpostgre-network:
    driver: bridge